apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::397450840647:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-IUKKVN9SAZ7U
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::397450840647:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-30T19:47:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1663"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6f7c1713-fb4b-4a06-9946-cdc8cb1cf5d7